### Registration
POST http://localhost:3001/user/register HTTP/1.1
Content-Type: application/json

{
    "firstname": "John","lastname": "Doe","dob": "2008-11-11","email": "john-doe@gmail.com","password":"test1234"
}

### Login with valid credentials
POST http://localhost:3001/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "john-doe@gmail.com","password":"test1234"
}

### Login with invalid credentials
POST http://localhost:3001/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "wrongemail@gmail.com","password":"wrongpassword"
}

###Get events
GET http://localhost:3001/events HTTP/1.1
Content-Type: application/json

###Add an Event
POST http://localhost:3001/events HTTP/1.1
Content-Type: application/json
Authorization: 

{
    "name": "Test Event","location": "Placeholder","description": "Placeholder","datetime": "2024-8-8", "photo": "", "user": {"id": 1}
}

###Search Events
POST http://localhost:3001/events/search HTTP/1.1
Content-Type: application/json

{
    "searchString": "test"
}

### Get all notifications
GET http://localhost:3001/notification/get HTTP/1.1

### Post notification
POST http://localhost:3001/notification/post HTTP/1.1
Content-Type: application/json

{
    "title": "Title",
    "description": "Test description",
    "datetime": "2201-04-12",
    "user_id": "1"
}

### Update notification
PUT http://localhost:3001/notification/update/2
Content-Type: application/json

{
  "title": "Updated Title",
  "description": "Updated Description",
  "datetime": "2202-04-12"
}

### Delete notification
DELETE http://localhost:3001/notification/delete/2


### Get all reviews
GET http://localhost:3001/review/get HTTP/1.1

### Post review
POST http://localhost:3001/review/post HTTP/1.1
Content-Type: application/json

{
    "title": "Review Title",
    "description": "Review Description",
    "rating": 4.5,
    "datetime": "2024-04-29",
    "user_id": 1,
    "event_id": 789012
}

### Update review
PUT http://localhost:3001/review/update/2
Content-Type: application/json

{
  "title": "Updated Title",
  "description": "Updated Description",
  "rating": 3,
  "datetime": "2202-04-12"
}

### Delete review
DELETE http://localhost:3001/review/delete/2